import './global.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import NavBar from './components/navbar';
import { Providers } from './providers';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <NavBar />
          <Providers> {children}</Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
